# https://travis-ci.org/evonove/django-oauth-toolkit
sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install coveralls tox tox-travis

script:
  - tox

after_script:
  - coveralls
