[tool.black]
line-length = 110
target-version = ['py38']
exclude = '''
^/(
        oauth2_provider/migrations/
    |   tests/migrations/
    |   .tox
)
'''

# Ref: https://github.com/codespell-project/codespell#using-a-config-file
[tool.codespell]
skip = '.git,package-lock.json'
check-hidden = true
# ignore-regex = ''
# ignore-words-list = ''
