# Ref: https://github.com/codespell-project/codespell#using-a-config-file
[tool.codespell]
skip = '.git,package-lock.json,locale,AUTHORS,tox.ini'
check-hidden = true
ignore-regex = '.*pragma: codespell-ignore.*'
ignore-words-list = 'assertIn'

[tool.ruff]
line-length = 110
exclude = [".tox", "build/", "dist/", "docs/", "oauth2_provider/migrations/", "tests/migrations/", "manage.py"]

[tool.ruff.lint]
select = ["E", "F", "I", "Q", "W"]

[tool.ruff.lint.isort]
lines-after-imports = 2
known-first-party = ["oauth2_provider"]
