# Generated by Django 5.2.17 on 2026-10-02 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("middle_name", models.CharField(blank=True, max_length=150)),
                ("nickname", models.CharField(blank=True, max_length=150)),
                ("profile", models.URLField(blank=True)),
                ("picture", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("gender", models.CharField(blank=True, max_length=64)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("zoneinfo", models.CharField(blank=True, max_length=64)),
                ("locale", models.CharField(blank=True, max_length=35)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email_verified", models.BooleanField(default=False)),
                ("phone_number", models.CharField(blank=True, max_length=32)),
                ("phone_number_verified", models.BooleanField(default=False)),
                ("street_address", models.TextField(blank=True)),
                ("locality", models.CharField(blank=True, max_length=255)),
                ("region", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=32)),
                ("country", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oidc_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
