# Generated by Django 5.0.7 on 2024-07-29 23:13

import hashlib
import logging

import oauth2_provider.models
from django.db import migrations, models
from oauth2_provider.settings import oauth2_settings

logger = logging.getLogger(__name__)


def forwards_func(apps, schema_editor):
    """
    Backfill token_checksum for existing access tokens.

    The checksum is computed explicitly instead of relying on
    TokenChecksumField.pre_save because bulk_update does not call pre_save.
    """
    AccessToken = apps.get_model(oauth2_settings.ACCESS_TOKEN_MODEL)
    db_alias = schema_editor.connection.alias
    if AccessToken._meta.label_lower != "oauth2_provider.accesstoken":
        # The access token model is swapped out. The schema operations in this
        # migration are skipped for swapped models, so the swapped app has to add
        # the field and backfill it in its own migration (see CHANGELOG).
        if AccessToken._default_manager.using(db_alias).exists():
            logger.warning(
                "Skipping the token_checksum backfill for swapped access token model %s. "
                "Existing access tokens will not validate until token_checksum is backfilled. "
                "Add a data migration to your app that backfills it; see the "
                "django-oauth-toolkit CHANGELOG for details.",
                AccessToken._meta.label,
            )
        return
    batch = []
    for accesstoken in AccessToken._default_manager.using(db_alias).only("pk", "token").iterator():
        accesstoken.token_checksum = hashlib.sha256(accesstoken.token.encode("utf-8")).hexdigest()
        batch.append(accesstoken)
        if len(batch) >= 1000:
            AccessToken._default_manager.using(db_alias).bulk_update(batch, ["token_checksum"])
            batch = []
    if batch:
        AccessToken._default_manager.using(db_alias).bulk_update(batch, ["token_checksum"])


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0011_refreshtoken_token_family"),
        migrations.swappable_dependency(oauth2_settings.ACCESS_TOKEN_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(blank=True, null=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="accesstoken",
            name="token",
            field=models.TextField(),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='accesstoken',
            name='token_checksum',
            field=oauth2_provider.models.TokenChecksumField(blank=False, max_length=64,  db_index=True, unique=True),
        ),
    ]
