# Generated by Django 5.1.2 on 2025-10-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0012_add_token_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="refreshtoken",
            name="token",
            field=models.CharField(max_length=8000),
        ),
    ]