# Generated by Django 5.2.9 on 2025-12-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0013_alter_application_authorization_grant_type_device"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="resource",
            field=models.TextField(blank=True, default=""),
        ),
    ]
