# Generated by Django 4.2.25 on 2026-01-12 21:00

from django.db import migrations
import oauth2_provider.models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0014_alter_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="grant",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="refreshtoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list),
        ),
    ]
