# Generated by Django 5.2.9 on 2025-12-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0014_grant_resource"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="resource",
            field=models.TextField(blank=True, default=""),
        ),
    ]
