# Generated by Django 5.2.15 on 2026-07-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2_provider", "0015_refreshtoken_token_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devicegrant",
            name="scope",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
