# Generated by Django 5.2 on 2026-07-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2_provider", "0020_cimd_application_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="require_pushed_authorization_requests",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Require this client to use Pushed Authorization Requests (RFC 9126). Leave unset to defer to the REQUIRE_PUSHED_AUTHORIZATION_REQUESTS setting.",
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="PushedAuthorizationRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("request_uri", models.CharField(max_length=255)),
                ("client_id", models.CharField(db_index=True, max_length=100)),
                ("parameters", models.JSONField(default=dict)),
                ("expires", models.DateTimeField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
                "swappable": "OAUTH2_PROVIDER_PAR_REQUEST_MODEL",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request_uri",),
                        name="oauth2_provider_pushedauthorizationrequest_unique_request_uri",
                    )
                ],
            },
        ),
    ]
