# Generated by Django 5.2.16 on 2026-07-24 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0020_cimd_application_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="client_jwks",
            field=models.TextField(
                blank=True,
                default="",
                help_text='The client\'s JSON Web Key Set (RFC 7517, {"keys": [...]}) holding the public keys used to verify private_key_jwt client assertions. Public keys only. Mutually exclusive with client_jwks_uri.',
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="client_jwks_uri",
            field=models.URLField(
                blank=True,
                default="",
                help_text="HTTPS URL of the client's JSON Web Key Set, fetched to verify private_key_jwt client assertions. Mutually exclusive with client_jwks.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="token_endpoint_auth_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Not set (infer from client type)"),
                    ("none", "None (public client)"),
                    ("client_secret_basic", "Client secret via HTTP Basic auth"),
                    ("client_secret_post", "Client secret in the request body"),
                    (
                        "client_secret_jwt",
                        "JWT assertion signed with the client secret",
                    ),
                    ("private_key_jwt", "JWT assertion signed with a private key"),
                ],
                default="",
                help_text="How the client authenticates to the token endpoint. Leave unset to keep the legacy behavior (client secret via Basic auth or request body for confidential clients). When a JWT method is selected the client must authenticate with an RFC 7523 client assertion and secret-based authentication is rejected.",
                max_length=32,
            ),
        ),
    ]
