# Generated by Django 5.2.17 on 2026-10-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0025_pushed_authorization_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="can_introspect",
            field=models.BooleanField(
                default=True,
                help_text="Allow this client to call the token introspection endpoint (RFC 7662) with an access token issued to it, or, if it is confidential, by authenticating as itself.",
                verbose_name="can introspect tokens",
            ),
        ),
    ]
