# Generated by Django 5.2.16 on 2026-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2_provider", "0025_pushed_authorization_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="jwt_access_token",
            field=models.BooleanField(
                default=False,
                help_text='Issue RFC 9068 JWT access tokens ("at+jwt") for this application, signed with its algorithm, instead of opaque random tokens.',
                verbose_name="JWT access token",
            ),
        ),
    ]
