# Generated by Django 5.2.17 on 2026-10-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0027_application_userinfo_signed_response_alg"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="client_uri",
            field=models.URLField(
                blank=True,
                default="",
                help_text="HTTPS URL of a web page with information about the client, shown on the consent page.",
                max_length=500,
                verbose_name="client URI",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="logo_uri",
            field=models.URLField(
                blank=True,
                default="",
                help_text="HTTPS URL of the client's logo image, shown on the consent page.",
                max_length=500,
                verbose_name="logo URI",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="policy_uri",
            field=models.URLField(
                blank=True,
                default="",
                help_text="HTTPS URL of the client's privacy policy, linked from the consent page.",
                max_length=500,
                verbose_name="policy URI",
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="tos_uri",
            field=models.URLField(
                blank=True,
                default="",
                help_text="HTTPS URL of the client's terms of service, linked from the consent page.",
                max_length=500,
                verbose_name="terms of service URI",
            ),
        ),
    ]
