# Generated by Django 5.2.17 on 2026-10-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0030_application_request_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="acr",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="authentication context class reference",
            ),
        ),
    ]
