# Generated by Django 5.2.17 on 2026-10-03 01:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("oauth2_provider", "0030_application_request_objects"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="consumed",
            field=models.DateTimeField(blank=True, null=True, verbose_name="consumed"),
        ),
        # Added without a default first: a callable default on AddField is evaluated once,
        # which would put every existing grant in the same token family, so a replay of
        # one code would revoke the tokens of every other. Existing grants keep NULL (no
        # family, nothing to revoke); the default then applies to new grants only.
        migrations.AddField(
            model_name="grant",
            name="token_family",
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name="token family"),
        ),
        migrations.AlterField(
            model_name="grant",
            name="token_family",
            field=models.UUIDField(
                blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name="token family"
            ),
        ),
    ]
