# Generated by Django 5.2.17 on 2026-10-08 17:16

import oauth2_provider.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2_provider", "0031_grant_acr"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="claims",
            field=oauth2_provider.models.ClaimsRequestJSONField(
                blank=True, default=dict, verbose_name="claims"
            ),
        ),
    ]
