# Generated by Django 5.2.17 on 2026-10-03 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauth2_provider", "0031_grant_acr"),
    ]

    operations = [
        migrations.AddField(
            model_name="accesstoken",
            name="claims",
            field=models.JSONField(blank=True, default=dict, verbose_name="claims"),
        ),
    ]
