# Generated by Django 5.2.15 on 2026-07-06 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import oauth2_provider.generators
import oauth2_provider.models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0010_refreshtoken_token_checksum"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetestapplication",
            name="allowed_origins",
            field=models.TextField(
                blank=True, default="", help_text="Allowed origins list to enable CORS, space separated"
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Client secret for authentication",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True, default="", help_text="Allowed Post Logout URIs list, space separated"
            ),
        ),
        migrations.AlterField(
            model_name="localidtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(db_index=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="allowed_origins",
            field=models.TextField(
                blank=True, default="", help_text="Allowed origins list to enable CORS, space separated"
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Client secret for authentication",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True, default="", help_text="Allowed Post Logout URIs list, space separated"
            ),
        ),
    ]
