# Generated by Django 5.2.15 on 2026-07-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0011_alter_basetestapplication_allowed_origins_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="scope",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
