# Generated by Django 5.2.15 on 2026-07-05 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0012_alter_sampledevicegrant_scope"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_AUTHORIZATION_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="custompkaccesstoken",
            name="authorization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_AUTHORIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="custompkrefreshtoken",
            name="authorization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_AUTHORIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="localidtoken",
            name="authorization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_AUTHORIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sampleaccesstoken",
            name="authorization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_AUTHORIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sampledevicegrant",
            name="authorization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_AUTHORIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="samplegrant",
            name="authorization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_AUTHORIZATION_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="samplegrant",
            name="exchanged_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="samplerefreshtoken",
            name="authorization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s",
                to=settings.OAUTH2_PROVIDER_AUTHORIZATION_MODEL,
            ),
        ),
    ]
