# Generated by Django 5.2 on 2026-07-06 21:01

import oauth2_provider.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0013_basetestapplication_dcr_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="custompkaccesstoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="custompkrefreshtoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="sampleaccesstoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="samplegrant",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="samplerefreshtoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(blank=True, default=list),
        ),
    ]
