# Generated by Django 5.2 on 2026-07-09 15:16

import oauth2_provider.generators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_registration_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetestapplication',
            name='cimd_expires_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the cached Client ID Metadata Document should be re-fetched', null=True),
        ),
        migrations.AddField(
            model_name='sampleapplication',
            name='cimd_expires_at',
            field=models.DateTimeField(blank=True, default=None, help_text='When the cached Client ID Metadata Document should be re-fetched', null=True),
        ),
        migrations.AlterField(
            model_name='basetestapplication',
            name='client_id',
            field=models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sampleapplication',
            name='client_id',
            field=models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=255, unique=True),
        ),
    ]
