# Generated by Django 5.2 on 2026-08-20 19:02

import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0016_basetestapplication_cimd_expires_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetestapplication",
            name="algorithm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No OIDC support"),
                    ("RS256", "RSA with SHA-2 256"),
                    ("HS256", "HMAC with SHA-2 256"),
                ],
                default="",
                max_length=5,
                verbose_name="algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed origins list to enable CORS, space separated",
                verbose_name="allowed origins",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
                verbose_name="authorization grant type",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="cimd_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the cached Client ID Metadata Document should be re-fetched",
                null=True,
                verbose_name="CIMD expires at",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default=oauth2_provider.generators.generate_client_id,
                max_length=255,
                unique=True,
                verbose_name="client ID",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Client secret for authentication",
                max_length=255,
                verbose_name="client secret",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="client_type",
            field=models.CharField(
                choices=[("confidential", "Confidential"), ("public", "Public")],
                max_length=32,
                verbose_name="client type",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="hash_client_secret",
            field=models.BooleanField(default=True, verbose_name="hash client secret"),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed Post Logout URIs list, space separated",
                verbose_name="post logout redirect URIs",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="redirect_uris",
            field=models.TextField(
                blank=True,
                help_text="Allowed URIs list, space separated",
                verbose_name="redirect URIs",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="registration_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("dcr", "Dynamic Client Registration"),
                    ("cimd", "Client ID Metadata Document"),
                ],
                default="manual",
                help_text="How this application was registered (manual, DCR per RFC 7591, or CIMD)",
                max_length=32,
                verbose_name="registration source",
            ),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="skip_authorization",
            field=models.BooleanField(default=False, verbose_name="skip authorization"),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="basetestapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="expires",
            field=models.DateTimeField(verbose_name="expires"),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(
                blank=True, default=list, verbose_name="resource"
            ),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="scope",
            field=models.TextField(blank=True, verbose_name="scope"),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="token",
            field=models.TextField(verbose_name="token"),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(
                db_index=True, max_length=64, unique=True, verbose_name="token checksum"
            ),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="custompkaccesstoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(
                blank=True, default=list, verbose_name="resource"
            ),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="revoked",
            field=models.DateTimeField(null=True, verbose_name="revoked"),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="token",
            field=models.TextField(verbose_name="token"),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(
                max_length=64, verbose_name="token checksum"
            ),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="token_family",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="token family"
            ),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="custompkrefreshtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="localidtoken",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="localidtoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="localidtoken",
            name="expires",
            field=models.DateTimeField(verbose_name="expires"),
        ),
        migrations.AlterField(
            model_name="localidtoken",
            name="scope",
            field=models.TextField(blank=True, verbose_name="scope"),
        ),
        migrations.AlterField(
            model_name="localidtoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="localidtoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="application",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="expires",
            field=models.DateTimeField(verbose_name="expires"),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(
                blank=True, default=list, verbose_name="resource"
            ),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="scope",
            field=models.TextField(blank=True, verbose_name="scope"),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="token",
            field=models.TextField(verbose_name="token"),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(
                db_index=True, max_length=64, unique=True, verbose_name="token checksum"
            ),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="sampleaccesstoken",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="algorithm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No OIDC support"),
                    ("RS256", "RSA with SHA-2 256"),
                    ("HS256", "HMAC with SHA-2 256"),
                ],
                default="",
                max_length=5,
                verbose_name="algorithm",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="allowed_origins",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed origins list to enable CORS, space separated",
                verbose_name="allowed origins",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                ],
                max_length=44,
                verbose_name="authorization grant type",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="cimd_expires_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="When the cached Client ID Metadata Document should be re-fetched",
                null=True,
                verbose_name="CIMD expires at",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="client_id",
            field=models.CharField(
                db_index=True,
                default=oauth2_provider.generators.generate_client_id,
                max_length=255,
                unique=True,
                verbose_name="client ID",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="client_secret",
            field=oauth2_provider.models.ClientSecretField(
                blank=True,
                db_index=True,
                default=oauth2_provider.generators.generate_client_secret,
                help_text="Client secret for authentication",
                max_length=255,
                verbose_name="client secret",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="client_type",
            field=models.CharField(
                choices=[("confidential", "Confidential"), ("public", "Public")],
                max_length=32,
                verbose_name="client type",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="hash_client_secret",
            field=models.BooleanField(default=True, verbose_name="hash client secret"),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="name",
            field=models.CharField(blank=True, max_length=255, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="post_logout_redirect_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Allowed Post Logout URIs list, space separated",
                verbose_name="post logout redirect URIs",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="redirect_uris",
            field=models.TextField(
                blank=True,
                help_text="Allowed URIs list, space separated",
                verbose_name="redirect URIs",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="registration_source",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("dcr", "Dynamic Client Registration"),
                    ("cimd", "Client ID Metadata Document"),
                ],
                default="manual",
                help_text="How this application was registered (manual, DCR per RFC 7591, or CIMD)",
                max_length=32,
                verbose_name="registration source",
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="skip_authorization",
            field=models.BooleanField(default=False, verbose_name="skip authorization"),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="client_id",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="client ID"
            ),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="device_code",
            field=models.CharField(max_length=100, verbose_name="device code"),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="expires",
            field=models.DateTimeField(verbose_name="expires"),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="interval",
            field=models.IntegerField(default=5, verbose_name="interval"),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="last_checked",
            field=models.DateTimeField(auto_now=True, verbose_name="last checked"),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="scope",
            field=models.TextField(blank=True, verbose_name="scope"),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("authorized", "Authorized"),
                    ("authorization-pending", "Authorization pending"),
                    ("expired", "Expired"),
                    ("denied", "Denied"),
                ],
                default="authorization-pending",
                max_length=64,
                verbose_name="status",
            ),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="sampledevicegrant",
            name="user_code",
            field=models.CharField(max_length=100, verbose_name="user code"),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="claims",
            field=models.TextField(blank=True, verbose_name="claims"),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="code",
            field=models.CharField(max_length=255, unique=True, verbose_name="code"),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="code_challenge",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="code challenge"
            ),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="code_challenge_method",
            field=models.CharField(
                blank=True,
                choices=[("plain", "plain"), ("S256", "S256")],
                default="",
                max_length=10,
                verbose_name="code challenge method",
            ),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="expires",
            field=models.DateTimeField(verbose_name="expires"),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="nonce",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="nonce"
            ),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="redirect_uri",
            field=models.TextField(verbose_name="redirect URI"),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(
                blank=True, default=list, verbose_name="resource"
            ),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="scope",
            field=models.TextField(blank=True, verbose_name="scope"),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="samplegrant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL,
                verbose_name="application",
            ),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="resource",
            field=oauth2_provider.models.ResourceJSONField(
                blank=True, default=list, verbose_name="resource"
            ),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="revoked",
            field=models.DateTimeField(null=True, verbose_name="revoked"),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="token",
            field=models.TextField(verbose_name="token"),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="token_checksum",
            field=oauth2_provider.models.TokenChecksumField(
                max_length=64, verbose_name="token checksum"
            ),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="token_family",
            field=models.UUIDField(
                blank=True, editable=False, null=True, verbose_name="token family"
            ),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="samplerefreshtoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
