# Generated by Django 5.2 on 2026-07-24 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0016_basetestapplication_cimd_expires_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetestapplication",
            name="require_pushed_authorization_requests",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Require this client to use Pushed Authorization Requests (RFC 9126). Leave unset to defer to the REQUIRE_PUSHED_AUTHORIZATION_REQUESTS setting.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="require_pushed_authorization_requests",
            field=models.BooleanField(
                blank=True,
                default=None,
                help_text="Require this client to use Pushed Authorization Requests (RFC 9126). Leave unset to defer to the REQUIRE_PUSHED_AUTHORIZATION_REQUESTS setting.",
                null=True,
            ),
        ),
    ]
