# Generated by Django 5.2 on 2026-07-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0017_testapps_client_assertion_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetestapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                    (
                        "urn:ietf:params:oauth:grant-type:jwt-bearer",
                        "JWT bearer (RFC 7523)",
                    ),
                ],
                max_length=44,
            ),
        ),
        migrations.AlterField(
            model_name="sampleapplication",
            name="authorization_grant_type",
            field=models.CharField(
                choices=[
                    ("authorization-code", "Authorization code"),
                    ("urn:ietf:params:oauth:grant-type:device_code", "Device Code"),
                    ("implicit", "Implicit"),
                    ("password", "Resource owner password-based"),
                    ("client-credentials", "Client credentials"),
                    ("openid-hybrid", "OpenID connect hybrid"),
                    (
                        "urn:ietf:params:oauth:grant-type:jwt-bearer",
                        "JWT bearer (RFC 7523)",
                    ),
                ],
                max_length=44,
            ),
        ),
    ]
