# Generated by Django 5.2.16 on 2026-08-21 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tests",
            "0021_basetestapplication_require_pushed_authorization_requests_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="basetestapplication",
            name="jwt_access_token",
            field=models.BooleanField(
                default=False,
                help_text='Issue RFC 9068 JWT access tokens ("at+jwt") for this application, signed with its algorithm, instead of opaque random tokens.',
                verbose_name="JWT access token",
            ),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="jwt_access_token",
            field=models.BooleanField(
                default=False,
                help_text='Issue RFC 9068 JWT access tokens ("at+jwt") for this application, signed with its algorithm, instead of opaque random tokens.',
                verbose_name="JWT access token",
            ),
        ),
    ]
