# Generated by Django 5.2 on 2026-08-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tests",
            "0021_basetestapplication_require_pushed_authorization_requests_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="basetestapplication",
            name="backchannel_logout_uri",
            field=models.URLField(
                blank=True,
                help_text="Backchannel Logout URI where logout tokens will be sent",
                null=True,
                verbose_name="backchannel logout uri",
            ),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="backchannel_logout_uri",
            field=models.URLField(
                blank=True,
                help_text="Backchannel Logout URI where logout tokens will be sent",
                null=True,
                verbose_name="backchannel logout uri",
            ),
        ),
    ]
