# Generated by Django 5.2.17 on 2026-10-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0022_application_can_introspect"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetestapplication",
            name="userinfo_signed_response_alg",
            field=models.CharField(
                blank=True,
                choices=[("", "No signing (JSON)"), ("RS256", "RSA with SHA-2 256")],
                default="",
                help_text="Sign UserInfo responses for this client as a JWT (OpenID Connect Core 1.0 section 5.3.2). Leave blank to return plain JSON.",
                max_length=5,
                verbose_name="UserInfo signing algorithm",
            ),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="userinfo_signed_response_alg",
            field=models.CharField(
                blank=True,
                choices=[("", "No signing (JSON)"), ("RS256", "RSA with SHA-2 256")],
                default="",
                help_text="Sign UserInfo responses for this client as a JWT (OpenID Connect Core 1.0 section 5.3.2). Leave blank to return plain JSON.",
                max_length=5,
                verbose_name="UserInfo signing algorithm",
            ),
        ),
    ]
