# Generated by Django 5.2.17 on 2026-10-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0024_application_client_display_metadata"),
    ]

    operations = [
        migrations.CreateModel(
            name="SampleStoredAuthorizationRequest",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "request_uri",
                    models.CharField(max_length=255, verbose_name="request URI"),
                ),
                (
                    "client_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="client id"
                    ),
                ),
                (
                    "parameters",
                    models.JSONField(default=dict, verbose_name="parameters"),
                ),
                ("expires", models.DateTimeField(verbose_name="expires")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                (
                    "custom_field",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("request_uri",),
                        name="tests_samplestoredauthorizationrequest_unique_request_uri",
                    )
                ],
            },
        ),
    ]
