# Generated by Django 5.2.17 on 2026-10-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tests", "0025_samplestoredauthorizationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="basetestapplication",
            name="request_object_signing_alg",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The JWS alg every request object from this client must be signed with ('none' for unsigned). Leave blank to accept any algorithm in OIDC_REQUEST_OBJECT_SIGNING_ALGS. Signed request objects are verified with client_jwks or client_jwks_uri.",
                max_length=10,
                verbose_name="request object signing alg",
            ),
        ),
        migrations.AddField(
            model_name="basetestapplication",
            name="request_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="HTTPS request_uri values this client may use to pass a request object by reference, space separated. When any are registered, a request_uri must match one of them (ignoring the fragment); when none are, any HTTPS request_uri is accepted.",
                verbose_name="request URIs",
            ),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="request_object_signing_alg",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The JWS alg every request object from this client must be signed with ('none' for unsigned). Leave blank to accept any algorithm in OIDC_REQUEST_OBJECT_SIGNING_ALGS. Signed request objects are verified with client_jwks or client_jwks_uri.",
                max_length=10,
                verbose_name="request object signing alg",
            ),
        ),
        migrations.AddField(
            model_name="sampleapplication",
            name="request_uris",
            field=models.TextField(
                blank=True,
                default="",
                help_text="HTTPS request_uri values this client may use to pass a request object by reference, space separated. When any are registered, a request_uri must match one of them (ignoring the fragment); when none are, any HTTPS request_uri is accepted.",
                verbose_name="request URIs",
            ),
        ),
    ]
