# Generated by Django 5.2.17 on 2026-10-08 17:16

import oauth2_provider.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests", "0027_samplegrant_acr"),
    ]

    operations = [
        migrations.AddField(
            model_name="custompkaccesstoken",
            name="claims",
            field=oauth2_provider.models.ClaimsRequestJSONField(
                blank=True, default=dict, verbose_name="claims"
            ),
        ),
        migrations.AddField(
            model_name="sampleaccesstoken",
            name="claims",
            field=oauth2_provider.models.ClaimsRequestJSONField(
                blank=True, default=dict, verbose_name="claims"
            ),
        ),
    ]
