"""Run the OpenID Foundation conformance suite against ``tests/app/idp``.

From the repository root (Docker and ``docker compose`` required)::

    tox -e openid-conformance-suite                      # every plan in PLANS
    tox -e openid-conformance-suite -- --plan basic      # one plan (repeatable); see --list-plans
    tox -e openid-conformance-suite -- --keep            # leave the stack running afterwards

What it does:

1. Generates a throwaway self-signed certificate for the IdP. The suite requires
   an https issuer but does not validate the certificate of the server under test.
2. Brings up the stack in ``docker-compose.yml``: the suite's prebuilt images
   pinned to ``--suite-version``, and the IdP built from this checkout.
3. Downloads the suite's own CI runner (``scripts/run-test-plan.py`` plus its two
   helper modules) at the same pinned tag, verifies their SHA-256, and runs the
   requested plans with their ``config/*.json`` and ``expected/*.json``.
4. Writes the exported results and the container logs to ``--export-dir``, then
   tears the stack down (unless ``--keep``).

The exit status is the runner's: non-zero on any failure or warning not listed in
the plan's ``expected/<name>.failures.json``, on a module skipped without an entry
in ``expected/<name>.skips.json``, on a listed failure or skip that did not occur,
or when a module did not run to completion. ``--verbose`` makes the runner print a
ready-made failures entry for every unexpected failure.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import ssl
import subprocess
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path


HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]

DEFAULT_SUITE_VERSION = "release-v5.3.1"
IDP_HOST = "dot-idp"
# Published on the host by docker-compose.yml purely for this readiness probe.
IDP_PROBE_URL = "https://127.0.0.1:9443/o/.well-known/openid-configuration"
# The suite's public base URL. In "dev mode" (CONFORMANCE_SERVER unset) the runner
# defaults to exactly this and skips TLS verification and the API token.
SUITE_URL = "https://localhost.emobix.co.uk:8443/"

COMPOSE_FILE = HERE / "docker-compose.yml"
# Relative to HERE: the runner's plan grammar only allows [A-Za-z0-9-_./] in a
# config path, so the absolute path of the checkout must not be part of it.
# The files are generated by config/generate.py; they differ in the alias and in
# the clients: the seeded pair for one grant type, or none, for the plans where
# the suite registers its own via RFC 7591.
STATIC_CONFIG = "config/dot-oidcc.json"
IMPLICIT_CONFIG = "config/dot-oidcc-implicit.json"
HYBRID_CONFIG = "config/dot-oidcc-hybrid.json"
DCR_CONFIG = "config/dot-oidcc-dcr.json"
# Per-plan calibration files: expected/<plan name>.failures.json and
# expected/<plan name>.skips.json, in the runner's own format. They are kept per
# plan because the runner fails a run whose entries match no module it ran.
EXPECTED_DIR = HERE / "expected"
CERTS_DIR = HERE / ".certs"
RUNNER_CACHE = HERE / ".runner"

RUNNER_RAW_URL = "https://gitlab.com/openid/conformance-suite/-/raw/{ref}/scripts/{name}"
# SHA-256 of the runner files at DEFAULT_SUITE_VERSION; bump both together
# (``curl -sSL <RUNNER_RAW_URL> | sha256sum``). Other versions are downloaded
# unverified, with a notice.
RUNNER_SCRIPTS = {
    "run-test-plan.py": "2abe903a8458efabda79e19dcb8f2be08a158fbe65d9e9169f1d6140fa36820e",
    "conformance.py": "660214cc6ca9b3c09297f61908a575db7b1552e8f44eecd5740d1c27fa2cfca8",
    "test_plan_parser.py": "2b00870b2dc46f1d44d047c715c0ef6978f24ece97a4a9d3b48ceeea8d01830f",
}

# Every OpenID Provider certification plan whose profile the toolkit implements,
# keyed by the short name used with --plan and in the CI matrix. Form Post,
# Session Management, Front-/Back-Channel Logout and 3rd-party initiated login
# are absent because the toolkit does not implement those specifications.
# A response type with a space is written as is: the grammar accepts the space
# inside the brackets and the value reaches the suite verbatim (the suite's own
# shell scripts escape it only for the shell's benefit).
PLANS = {
    "config": ("oidcc-config-certification-test-plan", STATIC_CONFIG),
    "basic": (
        "oidcc-basic-certification-test-plan[server_metadata=discovery][client_registration=static_client]",
        STATIC_CONFIG,
    ),
    "implicit": (
        "oidcc-implicit-certification-test-plan[server_metadata=discovery][client_registration=static_client]",
        IMPLICIT_CONFIG,
    ),
    "hybrid": (
        "oidcc-hybrid-certification-test-plan[server_metadata=discovery][client_registration=static_client]",
        HYBRID_CONFIG,
    ),
    "basic-dcr": (
        "oidcc-basic-certification-test-plan[server_metadata=discovery][client_registration=dynamic_client]",
        DCR_CONFIG,
    ),
    "implicit-dcr": (
        "oidcc-implicit-certification-test-plan[server_metadata=discovery][client_registration=dynamic_client]",
        DCR_CONFIG,
    ),
    "hybrid-dcr": (
        "oidcc-hybrid-certification-test-plan[server_metadata=discovery][client_registration=dynamic_client]",
        DCR_CONFIG,
    ),
    "dynamic": ("oidcc-dynamic-certification-test-plan[response_type=code]", DCR_CONFIG),
    "rp-initiated-logout": (
        "oidcc-rp-initiated-logout-certification-test-plan"
        "[response_type=code][client_registration=static_client]",
        STATIC_CONFIG,
    ),
    "rp-initiated-logout-dcr": (
        "oidcc-rp-initiated-logout-certification-test-plan"
        "[response_type=code id_token][client_registration=dynamic_client]",
        DCR_CONFIG,
    ),
}


def log(message: str) -> None:
    print(f"[openid-conformance-suite] {message}", flush=True)


def compose(
    *args: str, suite_version: str, check: bool = True, capture: bool = False
) -> subprocess.CompletedProcess:
    env = {**os.environ, "IMAGE_TAG": suite_version}
    return subprocess.run(
        ["docker", "compose", "-f", str(COMPOSE_FILE), *args],
        check=check,
        env=env,
        cwd=HERE,
        capture_output=capture,
        text=capture,
    )


def generate_certificate() -> None:
    """Write ``.certs/cert.pem`` + ``.certs/key.pem`` for ``IDP_HOST``.

    Reuses the e2e suite's generator; the repository root goes on ``sys.path`` only
    here so the module import does not have to precede this file's constants.
    """
    sys.path.insert(0, str(REPO_ROOT))
    from tests.e2e.helpers.tls import generate_self_signed_cert

    CERTS_DIR.mkdir(exist_ok=True)
    cert_path, key_path = generate_self_signed_cert(CERTS_DIR, [IDP_HOST, "localhost"])
    cert_path.replace(CERTS_DIR / "cert.pem")
    key_path.replace(CERTS_DIR / "key.pem")
    # The container reads the key as root; the generator's 0600 would hide it from
    # a rootless engine running the container as another uid.
    (CERTS_DIR / "key.pem").chmod(0o644)


def wait_for_idp(suite_version: str, timeout: float = 300.0) -> None:
    context = ssl.create_default_context()
    context.check_hostname = False
    context.verify_mode = ssl.CERT_NONE
    deadline = time.monotonic() + timeout
    while True:
        try:
            with urllib.request.urlopen(IDP_PROBE_URL, context=context, timeout=5) as response:
                if response.status == 200:
                    log(f"IdP is up: {IDP_PROBE_URL}")
                    return
        except (urllib.error.URLError, OSError, ConnectionError):
            # Not up yet (connection refused, TLS handshake before gunicorn
            # binds, or a 5xx while migrations run); fall through to the retry.
            pass
        if time.monotonic() > deadline:
            compose(
                "logs",
                "--no-color",
                "dot-idp",
                "idp-seed",
                "idp-migrate",
                suite_version=suite_version,
                check=False,
            )
            raise SystemExit(f"IdP did not become ready within {timeout:.0f}s")
        time.sleep(2)


def fetch_runner(ref: str) -> Path:
    """Download (and cache) the suite's CI runner scripts for ``ref``."""
    runner_dir = RUNNER_CACHE / ref
    runner_dir.mkdir(parents=True, exist_ok=True)
    verify = ref == DEFAULT_SUITE_VERSION
    if not verify:
        log(f"NOTE: no pinned checksums for {ref}; the runner scripts are not verified")
    for name, expected_sha256 in RUNNER_SCRIPTS.items():
        target = runner_dir / name
        if not target.exists():
            url = RUNNER_RAW_URL.format(ref=ref, name=name)
            log(f"fetching {url}")
            with urllib.request.urlopen(url, timeout=60) as response:
                target.write_bytes(response.read())
        if verify:
            actual = hashlib.sha256(target.read_bytes()).hexdigest()
            if actual != expected_sha256:
                target.unlink()
                raise SystemExit(f"checksum mismatch for {name}@{ref}: {actual} != {expected_sha256}")
    # run-test-plan.py lists this directory (client certificates for mTLS plans)
    # unconditionally, so it has to exist even though nothing here uses it.
    (runner_dir / "certs-keys").mkdir(exist_ok=True)
    return runner_dir


def run_plans(runner_dir: Path, plan_names: list[str], export_dir: Path, verbose: bool) -> int:
    command = [sys.executable, str(runner_dir / "run-test-plan.py"), "--export-dir", str(export_dir)]
    # The runner takes several files per option, "|"-separated.
    for option, suffix in (("--expected-failures-file", "failures"), ("--expected-skips-file", "skips")):
        files = [EXPECTED_DIR / f"{name}.{suffix}.json" for name in plan_names]
        files = [str(path) for path in files if path.exists()]
        if files:
            command += [option, "|".join(files)]
    if verbose:
        command.append("--verbose")
    for name in plan_names:
        command += list(PLANS[name])
    env = os.environ.copy()
    # Dev mode: the runner targets SUITE_URL without an API token.
    env.pop("CONFORMANCE_SERVER", None)
    env["PYTHONUNBUFFERED"] = "1"
    # The runner aborts the whole plan after N consecutive modules that did not
    # run to completion, to cut short a run against a dead server. Here a
    # cluster of modules hitting one OP gap is the normal case, and the report
    # for the rest of the plan is the point; the job timeout bounds the worst case.
    env.setdefault("CONFORMANCE_MAX_CONSECUTIVE_FAILURES", "25")
    log("running: " + " ".join(command[1:]))
    return subprocess.run(command, cwd=HERE, env=env, check=False).returncode


def collect_logs(export_dir: Path, suite_version: str) -> None:
    result = compose(
        "logs", "--no-color", "--timestamps", suite_version=suite_version, check=False, capture=True
    )
    (export_dir / "docker-compose.log").write_text(result.stdout + result.stderr)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--suite-version",
        default=os.environ.get("OPENID_CONFORMANCE_SUITE_VERSION", DEFAULT_SUITE_VERSION),
        help="conformance-suite git tag, used for the images and the runner scripts (default: %(default)s)",
    )
    parser.add_argument(
        "--plan",
        action="append",
        dest="plans",
        choices=sorted(PLANS),
        metavar="NAME",
        help="plan to run (repeatable); default: all of " + ", ".join(PLANS),
    )
    parser.add_argument("--list-plans", action="store_true", help="print the plans and exit")
    parser.add_argument(
        "--export-dir",
        type=Path,
        default=HERE / "reports",
        help="where the runner's exported results and the container logs go (default: %(default)s)",
    )
    parser.add_argument("--verbose", action="store_true", help="pass --verbose to run-test-plan.py")
    parser.add_argument(
        "--keep",
        action="store_true",
        help=f"leave the stack running afterwards (the suite UI is at {SUITE_URL})",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    if args.list_plans:
        for name, (plan, config_file) in PLANS.items():
            print(f"{name:24} {plan}  [{config_file}]")
        return 0
    plans = args.plans or list(PLANS)
    export_dir = args.export_dir.resolve()
    export_dir.mkdir(parents=True, exist_ok=True)

    generate_certificate()
    runner_dir = fetch_runner(args.suite_version)

    log(f"starting the stack (conformance-suite {args.suite_version})")
    compose("up", "--build", "--detach", suite_version=args.suite_version)
    try:
        wait_for_idp(args.suite_version)
        status = run_plans(runner_dir, plans, export_dir, args.verbose)
    finally:
        collect_logs(export_dir, args.suite_version)
        if args.keep:
            log(f"stack left running; suite UI: {SUITE_URL}  IdP: {IDP_PROBE_URL}")
        else:
            compose("down", "--volumes", "--remove-orphans", suite_version=args.suite_version, check=False)
    log(f"finished with exit status {status}; results in {export_dir}")
    return status


if __name__ == "__main__":
    sys.exit(main())
