name: Lint

on: [push, pull_request]

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install Ruff
      run: |
        python -m pip install ruff>=0.5
    - name: Format check (Ruff)
      run: |
        ruff format --check
